package com.machine.machine.constant

object ApiConst {
//    const val BASE_AUTH = "https://unyscapetech.com/machine/api/"
    const val BASE_AUTH = "https://machineapp.dci.in/api/"
    const val BASE_URL = "https://picsum.photos"
    const val BASE_MAP_URL = "https://maps.googleapis.com/"
    const val BASE_URL_2 = "https://reqres.in"
    const val GETPIC = "v2/list"
    const val LOGIN = "login"
    const val REGISTER_OTP = "login_via_otp"
    const val OTP_VERIFY = "login_via_otp/verify"
    const val FORGET_PASSWORD = "forgot_password"
    const val REGISTER = "update_account"
    const val CATEGORY_LIST = "products/category_listing"
    const val SUB_CATEGORY_LIST = "products/category_listing"
    const val EDIT_PROFILE = "update_account"
    const val CHANGE_PASSWORD = "update_account"
    const val HELP_AND_SUPPORT = "help_support_message"
    const val GET_HOME_DATA = "customer/home"
    const val GET_SHOP_FAVOURITE_LIST = "customer/shop/favourites"
    const val GET_SETTING_ME = "me"
    const val NOTIFICATION = "settings"
    const val CATEGORY_SHOP_LISTING_BY_ID = "customer/shop"
    const val ADD_SHOP_TO_FAV = "customer/shop/add_to_favourite"
    const val ADD_PRODUCT_TO_FAV = "customer/products/add_to_favourite"
    const val GET_SHOP_DETAIL = "customer/shop/detail"
    const val GET_PRODUCT_LIST_BY_CAT_ID = "products"
    const val GET_PRODUCT_FAVOURITE_LIST = "customer/products/favourites"
    const val GET_PRODUCT_DETAIL = "products/detail"
    const val LOGOUT = "logout"
    const val GET_ALL_CART_ITEM_LISTING = "customer/cart"
    const val ADD_TO_CART_ITEM = "customer/cart/add_to_cart"
    const val REMOVE_CART_ITEM = "customer/cart/remove_from_cart"
    const val GET_ALL_ADDRESS = "customer/address"
    const val ADD_NEW_ADDRESS = "customer/address/create"
    const val UPDATE_ADDRESS = "customer/address/update"
    const val SET_AS_PRIMARY_ADDRESS = "customer/address/update"
    const val DELETE_ADDRESS = "customer/address/delete"
    const val GET_ADDRESS_BY_ID = "customer/address/view"
    const val GET_SELLER_SHOPS = "seller/shop"
    const val GET_SELLER_RFQ = "seller/order/quotations"
    const val GET_SELLER_DETAILS_RFQ = "seller/order/quotation_detail"
    const val GET_CUSTOMER_DETAILS_RFQ = "customer/order/quotation_detail"

    const val ALL_PRODUCTS = "seller/product"
    const val UPDATE_PRODUCT = "seller/product/update"
    const val REMOVE_PRODUCT = "seller/product/delete"
    const val CREATE_NEW_SHOP = "seller/shop/store"
    const val SUBMIT_QUOTATION = "customer/order/submit_quotation"
    const val GET_CHAT_LIST = "chat"
    const val GET_CHATS = "chat/view_channel"
    const val Create_Chat = "chat/create_channel"
    const val SEND_MESSAGES = "chat/messages"
    const val BID_UPDATE = "seller/order/accept_reject_bid"
    const val customerNotification = "customer/notifications"
    const val customerNotificationRead = "customer/notifications-read"
    const val sellerNotification = "seller/notifications"
    const val sellerNotificationRead = "seller/notifications-read"
    const val acceptRejectQuotation = "seller/order/accept_reject_quotation"
    const val getCustomerMessageCount = "customer/get-message-count"
    const val getSellerMessageAndQuotationCount = "seller/get-message-order-count"
    const val distanceMatrixGoogleApi = "maps/api/distancematrix/json"

}